Repository MemoBlend/MemoBlend4J, pull requests merged in 2025-05, with the labels that each got.

#398 Blank Issueの作成を禁止
  .github/ISSUE_TEMPLATE/config.yml
Labels: 開発環境改善

#412 Collectors.toList()をStream.toList()に置換
  backend/web/src/main/java/com/memoblend/web/auth/UserStoreImpl.java
Labels: バックエンドアプリケーション

#413 複数回同じリテラルを呼び出さないよう修正
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Content.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Name.java
Labels: バックエンドアプリケーション

#414 不要な一時変数を削除
  backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/UserApplicationServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryDomainServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserDomainServiceTest.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/MyBatisDiaryRepository.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/MyBatisUserRepository.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/GetDiariesResponseMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/GetDiaryReponseMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PostDiaryRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PutDiaryRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/GetUserReponseMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/GetUsersResponseMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PostUserRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PutUserRequestMapper.java
Labels: バックエンドアプリケーション

#415 テストクラスの不要な修飾子を削除
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/UserApplicationServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryDomainServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserDomainServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java
  backend/web/src/test/java/com/memoblend/web/WebApplicationTests.java
  backend/web/src/test/java/com/memoblend/web/controller/DiaryControllerTest.java
  backend/web/src/test/java/com/memoblend/web/controller/UserControllerTest.java
Labels: バックエンドアプリケーション

#416 一部のテストをパラメタライズテストに置換
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java
Labels: バックエンドアプリケーション

#417 bool値の返却を条件式に置換
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryDomainService.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserDomainService.java
Labels: バックエンドアプリケーション

#418 該当のクラスにプライベートコンストラクタを追加
  backend/application-core/src/main/java/com/memoblend/applicationcore/constant/ExceptionIdConstants.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/constant/MessageIdConstants.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/constant/UserRoleConstants.java
  backend/system-common/src/main/java/com/memoblend/systemcommon/constant/CommonExceptionIdConstants.java
  backend/web/src/main/java/com/memoblend/web/constant/WebConstants.java
  backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java
  backend/web/src/main/java/com/memoblend/web/controller/UserController.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/GetDiariesResponseMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/GetDiaryResponseMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PostDiaryRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PutDiaryRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/GetUserResponseMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/GetUsersResponseMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PostUserRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PutUserRequestMapper.java
Labels: バックエンドアプリケーション

#421 二重括弧の初期化は使用しないよう修正
  backend/web/src/main/java/com/memoblend/web/controller/util/ProblemDetailsFactory.java
Labels: バックエンドアプリケーション

#422 一部の匿名内部クラスをラムダ式に置換
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/config/MyBatisConfig.java
Labels: バックエンドアプリケーション

#434 空のメソッドにコメントを追加
  backend/web/src/test/java/com/memoblend/web/WebApplicationTests.java
Labels: バックエンドアプリケーション

#427 プライベートコンストラクタの対応漏れに対応
  backend/system-common/src/main/java/com/memoblend/systemcommon/constant/SystemPropertyConstants.java
Labels: バックエンドアプリケーション

#423 一部のフィールドをfinal化
  backend/system-common/src/main/java/com/memoblend/systemcommon/exception/LogicException.java
  backend/system-common/src/main/java/com/memoblend/systemcommon/exception/SystemException.java
Labels: バックエンドアプリケーション

#435 定数名の命名規則を修正
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Content.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Name.java
Labels: バックエンドアプリケーション

#436 不要な型キャストを削除
  backend/web/src/main/java/com/memoblend/web/log/ErrorMessageBuilder.java
Labels: バックエンドアプリケーション

#437 不要な型指定を削除
  backend/web/src/main/java/com/memoblend/web/controller/util/ProblemDetailsFactory.java
Labels: バックエンドアプリケーション

#438 filter().findFirst().isPresent()をanyMatch()に置換
  backend/web/src/main/java/com/memoblend/web/controller/util/ProblemDetailsFactory.java
Labels: バックエンドアプリケーション

#396 フォルダ構成の変更
  analysisapi/.gitignore
  analysisapi/analysisapi/ai_processor/diary_analyzer.py
  analysisapi/analysisapi/ai_processor/text_vectorizer.py
  analysisapi/analysisapi/cli.py
  analysisapi/analysisapi/loader/__init__.py
  analysisapi/analysisapi/loader/config_loader.py
  analysisapi/analysisapi/tests/__init__.py
  analysisapi/config.xml
  analysisapi/generateopenapi/cli.py
  analysisapi/requirements.txt
  analysisapi/scheduleplanner/applicationcore/abstractrepository/abstract_chromadb_repository.py
  analysisapi/scheduleplanner/applicationcore/applicationservice/application_service.py
  analysisapi/scheduleplanner/applicationcore/client/_ai/scheduler.py
  analysisapi/scheduleplanner/applicationcore/client/restaurant/restaurant_client.py
  analysisapi/scheduleplanner/applicationcore/client/weather/loader/jma_loader.py
  analysisapi/scheduleplanner/applicationcore/client/weather/weather_client.py
  analysisapi/scheduleplanner/applicationcore/property/jma_codes.json
  analysisapi/scheduleplanner/infrastructure/chromadb_repository.py
  analysisapi/scheduleplanner/web/__init__.py
  analysisapi/scheduleplanner/web/__main__.py
  analysisapi/scheduleplanner/web/controller.py
  analysisapi/scheduleplanner/web/loader/config_loader.py
  analysisapi/scheduleplanner/web/property/config.xml
Labels: AI

#445 空のメソッドへの追加対応
  backend/web/src/test/java/com/memoblend/web/WebApplicationTests.java
Labels: バックエンドアプリケーション

#432 ドキュメント生成機能の実装
  analysisapi/scheduleplanner/__init__.py
  analysisapi/scheduleplanner/__main__.py
  analysisapi/scheduleplanner/applicationcore/__init__.py
  analysisapi/scheduleplanner/applicationcore/abstractrepository/abstract_chromadb_repository.py
  analysisapi/scheduleplanner/applicationcore/applicationservice/__init__.py
  analysisapi/scheduleplanner/applicationcore/applicationservice/application_service.py
  analysisapi/scheduleplanner/applicationcore/client/__init__.py
  analysisapi/scheduleplanner/applicationcore/client/restaurant/__init__.py
  analysisapi/scheduleplanner/applicationcore/client/weather/__init__.py
  analysisapi/scheduleplanner/applicationcore/client/weather/weather_client.py
  analysisapi/scheduleplanner/infrastructure/__init__.py
  analysisapi/scheduleplanner/infrastructure/chromadb_repository.py
  analysisapi/scheduleplanner/web/controller.py
  analysisapi/scheduleplanner/web/loader/__init__.py
Labels: 開発環境改善, AI

#444 READMEにAIサーバー起動方法を追記
  README.md
Labels: AI, リリース対応

#447 dependabotの上限を変更
  .github/dependabot.yml
Labels: 開発環境改善

#456 Dependabot Updateの最大数を追加
  .github/dependabot.yml
Labels: 開発環境改善

#476 Chroma DBの出力階層修正
  analysisapi/scheduleplanner/infrastructure/chromadb_repository.py
Labels: バグ, AI

#490 extension.jsonとsettings.jsonの追加
  analysisapi/.vscode/extensions.json
  analysisapi/.vscode/settings.json
Labels: 開発環境改善

#493 Javaプログラムのリファクタリングを実施
  backend/web/src/main/java/com/memoblend/web/auth/UserStoreImpl.java
  backend/web/src/main/java/com/memoblend/web/filter/DummyUserInjectionFilter.java
  backend/web/src/main/java/com/memoblend/web/log/ErrorMessageBuilder.java
  backend/web/src/main/java/com/memoblend/web/security/WebSecurityConfig.java
Labels: 開発環境改善

#494 User-Agentを設定しないようpackage.jsonの書き換え
  frontend/diary/package.json
  frontend/diary/src/generated/api-client/configuration.ts
Labels: フロントエンドアプリケーション, バグ

#478 scheduleplannerのリファクタリング
  analysisapi/scheduleplanner/applicationcore/__init__.py
  analysisapi/scheduleplanner/applicationcore/applicationservice/__init__.py
  analysisapi/scheduleplanner/applicationcore/applicationservice/application_service.py
  analysisapi/scheduleplanner/applicationcore/client/__init__.py
  analysisapi/scheduleplanner/applicationcore/client/_ai/scheduler.py
  analysisapi/scheduleplanner/applicationcore/client/restaurant/__init__.py
  analysisapi/scheduleplanner/applicationcore/client/weather/__init__.py
  analysisapi/scheduleplanner/applicationcore/client/weather/loader/jma_loader.py
  analysisapi/scheduleplanner/applicationcore/client/weather/weather_client.py
  analysisapi/scheduleplanner/applicationcore/constant/applicationservice_constants.py
  analysisapi/scheduleplanner/applicationcore/property/jma_codes.json
  analysisapi/scheduleplanner/infrastructure/__init__.py
  analysisapi/scheduleplanner/infrastructure/chromadb_repository.py
  analysisapi/scheduleplanner/web/__init__.py
  analysisapi/scheduleplanner/web/controller.py
  analysisapi/scheduleplanner/web/loader/__init__.py
  analysisapi/scheduleplanner/web/loader/config_loader.py
Labels: 開発環境改善, AI

#515 pythonプロジェクトの静的解析ツールの解析結果をコードに反映
  analysisapi/.gitignore
  analysisapi/.vscode/settings.json
  analysisapi/api-docs/analysisapi/api-specification.json
  analysisapi/app.py
  analysisapi/applicationcore/client_application_service.py
  analysisapi/applicationcore/diary_application_service.py
  analysisapi/applicationcore/prompt_constants.py
  analysisapi/generateopenapi/__main__.py
  analysisapi/generateopenapi/cli.py
  analysisapi/generateopenapi/constants.py
  analysisapi/generateopenapi/generate_openapi.py
  analysisapi/infrastructure/client/client_constants.py
  analysisapi/infrastructure/client/client_openai.py
  analysisapi/infrastructure/client/client_restaurant.py
  analysisapi/infrastructure/client/client_weather.py
  analysisapi/infrastructure/diary_repository.py
  analysisapi/infrastructure/infrastructure_constants.py
  analysisapi/presentation/controller.py
  analysisapi/presentation/presentation_constants.py
  analysisapi/requirements.txt
  analysisapi/scheduleplanner/__main__.py
  analysisapi/scheduleplanner/applicationcore/applicationservice/application_service.py
  analysisapi/scheduleplanner/applicationcore/client/restaurant/restaurant_client.py
  analysisapi/scheduleplanner/applicationcore/client/weather/weather_client.py
  analysisapi/scheduleplanner/applicationcore/constant/applicationservice_constants.py
  analysisapi/scheduleplanner/config/logger_config.py
  analysisapi/scheduleplanner/infrastructure/chromadb_repository.py
  analysisapi/scheduleplanner/web/controller.py
  analysisapi/scheduleplanner/web/loader/config_loader.py
  analysisapi/scheduleplanner/web/property/config.xml
  analysisapi/settings.py
  analysisapi/systemcommon/logger_config.py
Labels: AI

#520 業務例外の共通クラスを作成
  analysisapi/app.py
  analysisapi/applicationcore/client_application_service.py
  analysisapi/applicationcore/collection_load_failed_exception.py
  analysisapi/applicationcore/diary_application_service.py
  analysisapi/applicationcore/prompt_constants.py
  analysisapi/generateopenapi/constants.py
  analysisapi/infrastructure/client/client_constants.py
  analysisapi/infrastructure/client/client_openai.py
  analysisapi/infrastructure/client/client_weather.py
  analysisapi/infrastructure/diary_repository.py
  analysisapi/infrastructure/infrastructure_constants.py
  analysisapi/presentation/controller.py
  analysisapi/presentation/exception_handlers.py
  analysisapi/presentation/presentation_constants.py
  analysisapi/requirements.txt
  analysisapi/systemcommon/business_exception.py
  analysisapi/systemcommon/logger_config.py
  analysisapi/systemcommon/system_exception.py
Labels: AI

#522 not foundページを実装
  frontend/diary/src/router/error/index.ts
  frontend/diary/src/router/index.ts
  frontend/diary/src/views/error/NotFoundView.vue
Labels: フロントエンドアプリケーション
