Repository MemoBlend/MemoBlend4J, pull requests merged in 2025-06, with the labels that each got.

#481 全国の明日の天気をjsonファイルに保存する機能の実装
  analysisapi/fetchforecastbatch/.gitignore
  analysisapi/fetchforecastbatch/__init__.py
  analysisapi/fetchforecastbatch/__main__.py
  analysisapi/fetchforecastbatch/app.py
  analysisapi/fetchforecastbatch/forecast_client.py
  analysisapi/fetchforecastbatch/property/city_ids.json
Labels: AI

#570 spring dev toolsの利用を検討する
  backend/dependencies.gradle
  backend/web/build.gradle
  backend/web/src/main/resources/application-dev.properties
Labels: バックエンドアプリケーション, 開発環境改善

#574 リリースノートテンプレートの不適当に対応
  .github/release.yml
Labels: バグ

#572 日記の月ごと取得の分析aiの修正をしたい
  analysisapi/presentation/controller.py
  analysisapi/presentation/presentation_constants.py
Labels: AI

#588 コミットメッセージ生成の指示を日本語で追加
  analysisapi/.vscode/settings.json
  backend/.vscode/settings.json
  frontend/diary/.vscode/settings.json
Labels: 開発環境改善

#593 日記の分析結果を取得する機能をバックエンドに追加
  backend/api-docs/web/api-specification.json
  backend/application-core/build.gradle
  backend/application-core/src/main/java/com/memoblend/applicationcore/api/DiaryAnalysisApiClient.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/constant/MessageIdConstants.java
  backend/application-core/src/main/resources/applicationcore/messages.properties
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/api/DiaryAnalysisApiClientImpl.java
  backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java
  backend/web/src/main/java/com/memoblend/web/controller/dto/diary/GetRecommendedScheduleResponse.java
  backend/web/src/test/java/com/memoblend/web/controller/DiaryControllerTest.java
Labels: バックエンドアプリケーション, AI
