Repository MemoBlend/MemoBlend4J, pull requests merged in 2025-04, with the labels that each got.

#358 RAGの基盤コード作成
  analysisapi/.gitignore
  analysisapi/Pipfile
  analysisapi/Pipfile.lock
  analysisapi/README.md
  analysisapi/analysisapi/ai_processor/diary_analyzer.py
  analysisapi/analysisapi/cli.py
  analysisapi/config.xml
  analysisapi/requirements.txt
Labels: AI

#367 FastAPIのAPI定義書自動生成機能の実装
  analysisapi/README.md
  analysisapi/analysisapi/cli.py
  analysisapi/api-docs/analysisapi/api-specification.json
  analysisapi/generateopenapi/__init__.py
  analysisapi/generateopenapi/__main__.py
  analysisapi/generateopenapi/cli.py
Labels: 開発環境改善, AI

#380 Copilotのレビュを日本語に変更
  .github/pull_request_template.md
Labels: 開発環境改善

#377 OpenAPI出力の修正
  analysisapi/api-docs/analysisapi/api-specification.json
  analysisapi/generateopenapi/cli.py
Labels: AI

#376 ChromaDBの実装
  analysisapi/analysisapi/ai_processor/diary_analyzer.py
  analysisapi/analysisapi/ai_processor/text_vectorizer.py
  analysisapi/analysisapi/cli.py
  analysisapi/requirements.txt
Labels: AI

#384 RAGの実装
  analysisapi/analysisapi/ai_processor/diary_analyzer.py
  analysisapi/analysisapi/ai_processor/text_vectorizer.py
Labels: AI

#386 fast API依存関係の解決
  analysisapi/requirements.txt
Labels: AI

#388 リファクタリングを行う
  backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/UserApplicationService.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/Diary.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryValidationException.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Id.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/IsDeleted.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/UserId.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserValidationException.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Id.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/IsDeleted.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.xml
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.xml
  backend/system-common/src/main/java/com/memoblend/systemcommon/exception/LogicException.java
  backend/system-common/src/main/java/com/memoblend/systemcommon/exception/SystemException.java
  backend/system-common/src/main/java/com/memoblend/systemcommon/exception/ValidationException.java
  backend/web/src/main/java/com/memoblend/web/controller/advice/ExceptionHandlerControllerAdvice.java
  backend/web/src/main/java/com/memoblend/web/filter/DummyUserInjectionFilter.java
  frontend/diary/src/components/atoms/Event/Event.vue
  frontend/diary/src/components/organisms/Calendar/Calendar.vue
  frontend/diary/src/router/authentication/index.ts
  frontend/diary/src/router/diary/index.ts
  frontend/diary/src/router/error/index.ts
  frontend/diary/src/shared/authentication/authentication-guard.ts
  frontend/diary/src/views/authentication/LoginView.vue
  frontend/diary/src/views/diary/DiariesView.vue
  frontend/diary/src/views/diary/DiaryDetailView.vue
Labels: 開発環境改善
