Repository MemoBlend/MemoBlend4J, pull requests merged in 2025-03, with the labels that each got.

#203 日記ドメインの単体テスト実装
  backend/api-docs/web/api-specification.json
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/Diary.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryTest.java
Labels: backend

#214 画面を整形
  frontend/diary/src/App.vue
  frontend/diary/src/components/atoms/DiaryIcon.vue
  frontend/diary/src/components/atoms/HamburgerMenuIcon.vue
  frontend/diary/src/components/atoms/XMarkIcon.vue
  frontend/diary/src/views/diary/DiariesView.vue
  frontend/diary/src/views/diary/DiaryCreateView.vue
  frontend/diary/src/views/diary/DiaryDeleteView.vue
  frontend/diary/src/views/diary/DiaryDetailView.vue
  frontend/diary/src/views/diary/DiaryEditView.vue
  frontend/package-lock.json
Labels: frontend, 開発環境改善

#221 ユーザードメインの単体テスト実装
  backend/api-docs/web/api-specification.json
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java
Labels: backend

#222 日記の削除処理をモーダルで制御する
  frontend/diary/src/api-client/index.ts
  frontend/diary/src/components/ConfirmationModal.vue
  frontend/diary/src/router/index.ts
  frontend/diary/src/services/diary/diary-service.ts
  frontend/diary/src/views/diary/DiariesView.vue
  frontend/diary/src/views/diary/DiaryCreateView.vue
  frontend/diary/src/views/diary/DiaryDeleteView.vue
  frontend/diary/src/views/diary/DiaryDetailView.vue
  frontend/diary/src/views/diary/DiaryEditView.vue
Labels: frontend

#237 スタイルをtailwindcssからvuetifyに移行
  frontend/.stylelintrc.js
  frontend/diary/src/App.vue
  frontend/diary/src/assets/base.css
  frontend/diary/src/components/ConfirmationModal.vue
  frontend/diary/src/main.ts
  frontend/diary/src/views/diary/DiariesView.vue
  frontend/diary/src/views/diary/DiaryCreateView.vue
  frontend/diary/src/views/diary/DiaryDetailView.vue
  frontend/diary/src/views/diary/DiaryEditView.vue
  frontend/diary/vite.config.ts
  frontend/package-lock.json
  frontend/package.json
Labels: frontend, 開発環境改善

#224 ユーザー論理削除機能実装
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserDomainService.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/UserApplicationServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserDomainServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.xml
  backend/infrastructure/src/main/resources/data.sql
  backend/infrastructure/src/main/resources/schema.sql
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PostUserRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PutUserRequestMapper.java
Labels: backend

#241 ダミーデータの追加
  backend/infrastructure/src/main/resources/data.sql
Labels: 開発環境改善

#246 日記の一覧をカレンダー表示に修正
  frontend/diary/index.html
  frontend/diary/src/components/atoms/Event/Event.vue
  frontend/diary/src/components/atoms/Event/index.ts
  frontend/diary/src/components/molecules/EventList/EventList.vue
  frontend/diary/src/components/molecules/EventList/index.ts
  frontend/diary/src/components/organisms/Calendar/Calendar.vue
  frontend/diary/src/components/organisms/Calendar/index.ts
  frontend/diary/src/main.ts
  frontend/diary/src/types/index.ts
  frontend/diary/src/views/diary/DiariesView.vue
Labels: フロントエンドアプリケーション

#252 例外の捕捉環境を整える
  frontend/diary/src/main.ts
  frontend/diary/src/router/index.ts
  frontend/diary/src/shared/error-handler/custom-error-handler.ts
  frontend/diary/src/shared/error-handler/custom-error.ts
  frontend/diary/src/shared/error-handler/global-error-handler.ts
  frontend/diary/src/shared/error-handler/injection-symbols.ts
  frontend/diary/src/shared/error-handler/use-custom-error-handler.ts
  frontend/diary/src/views/diary/DiariesView.vue
  frontend/diary/src/views/diary/DiaryCreateView.vue
  frontend/diary/src/views/diary/DiaryDetailView.vue
  frontend/diary/src/views/diary/DiaryEditView.vue
  frontend/diary/src/views/error/ErrorView.vue
Labels: フロントエンドアプリケーション

#253 フッターの追加
  frontend/diary/src/App.vue
  frontend/diary/src/views/diary/DiariesView.vue
Labels: フロントエンドアプリケーション

#255 メニューバーの有効化
  frontend/diary/src/App.vue
Labels: フロントエンドアプリケーション

#257 apiコール中にスピナーを表示したい
  frontend/diary/src/App.vue
  frontend/diary/src/components/organisms/LoadingSpinnerOverlay/LoadingSpinnerOverlay.vue
  frontend/diary/src/components/organisms/LoadingSpinnerOverlay/index.ts
  frontend/diary/src/views/diary/DiariesView.vue
  frontend/diary/src/views/diary/DiaryDetailView.vue
  frontend/diary/src/views/diary/DiaryEditView.vue
Labels: フロントエンドアプリケーション

#243 日記に論理削除機能を実装
  backend/api-docs/web/api-specification.json
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/Diary.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryDomainService.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryDomainServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryTest.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.xml
  backend/infrastructure/src/main/resources/data.sql
  backend/infrastructure/src/main/resources/schema.sql
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PostDiaryRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PutDiaryRequestMapper.java
Labels: バックエンドアプリケーション

#259 userMapperを論理削除仕様に修正
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.xml
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.xml
Labels: バックエンドアプリケーション

#265 fast apiのひな型作成
  analysisapi/.gitignore
  analysisapi/Pipfile
  analysisapi/Pipfile.lock
  analysisapi/README.md
  analysisapi/config.xml
  analysisapi/main.py
Labels: AI

#266 Userエンティティの定数管理対応
  backend/application-core/src/main/java/com/memoblend/applicationcore/constant/ExceptionIdConstants.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java
  backend/application-core/src/main/resources/applicationcore/messages.properties
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java
Labels: バックエンドアプリケーション

#286 アプリの実行手順を追記
  README.md
Labels: 開発環境改善

#289 pythonバージョン指定方法変更
  analysisapi/Pipfile
  analysisapi/Pipfile.lock
Labels: AI

#309 gradleの設定ファイルを微修正
  backend/build.gradle
  backend/dependencies.gradle
Labels: バックエンドアプリケーション, 開発環境改善

#310 gradle version catalogの導入を検討する
  backend/build.gradle
  backend/dependencies.gradle
Labels: バックエンドアプリケーション, 開発環境改善

#308 不要なimportを削除
  frontend/diary/src/components/molecules/EventList/EventList.vue
Labels: フロントエンドアプリケーション, バグ

#306 日記の値オブジェクトを実装
  backend/api-docs/web/api-specification.json
  backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/Diary.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryDomainService.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Content.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/CreatedDate.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Id.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/IsDeleted.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Title.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/UserId.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryDomainServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryTest.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.xml
  backend/infrastructure/src/main/resources/data.sql
  backend/infrastructure/src/main/resources/schema.sql
  backend/web/src/main/java/com/memoblend/web/controller/dto/diary/GetDiaryResponse.java
  backend/web/src/main/java/com/memoblend/web/controller/dto/diary/PostDiaryRequest.java
  backend/web/src/main/java/com/memoblend/web/controller/dto/diary/PutDiaryRequest.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/GetDiaryReponseMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PostDiaryRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PutDiaryRequestMapper.java
  backend/web/src/test/java/com/memoblend/web/controller/DiaryControllerTest.java
Labels: バックエンドアプリケーション

#314 SpotBugsのツールバージョン
  backend/dependencies.gradle
Labels: バグ

#288 ユーザーの値オブジェクトの実装
  backend/application-core/src/main/java/com/memoblend/applicationcore/constant/ExceptionIdConstants.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserDomainService.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Id.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/IsDeleted.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Name.java
  backend/application-core/src/main/resources/applicationcore/messages.properties
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/UserApplicationServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserDomainServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.xml
Labels: バックエンドアプリケーション

#323 フロントエンドで発生している警告に対応
  frontend/diary/src/generated/api-client/api/user-api.ts
  frontend/diary/src/generated/api-client/models/diary.ts
  frontend/diary/src/generated/api-client/models/get-diary-response.ts
  frontend/diary/src/generated/api-client/models/post-diary-request.ts
  frontend/diary/src/generated/api-client/models/put-diary-request.ts
  frontend/diary/src/main.ts
  frontend/diary/src/views/diary/DiariesView.vue
  frontend/diary/src/views/diary/DiaryCreateView.vue
Labels: バグ

#326 例外メッセージの定数管理を集約
  backend/application-core/src/main/java/com/memoblend/applicationcore/constant/ExceptionIdConstants.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/Diary.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryValidationException.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Content.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/CreatedDate.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Id.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Title.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/UserId.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserValidationException.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Id.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/IsDeleted.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Name.java
  backend/application-core/src/main/resources/applicationcore/messages.properties
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/UserApplicationServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryDomainServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserDomainServiceTest.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java
  backend/system-common/src/main/java/com/memoblend/systemcommon/exception/ValidationException.java
  backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java
  backend/web/src/main/java/com/memoblend/web/controller/UserController.java
  backend/web/src/main/java/com/memoblend/web/controller/advice/ExceptionHandlerControllerAdvice.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PostDiaryRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PutDiaryRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PostUserRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PutUserRequestMapper.java
  backend/web/src/main/java/com/memoblend/web/log/ErrorMessageBuilder.java
  frontend/diary/src/views/diary/DiaryDetailView.vue
  frontend/diary/src/views/diary/DiaryEditView.vue
Labels: バックエンドアプリケーション, バグ

#325 package実行に修正
  analysisapi/.gitignore
  analysisapi/Pipfile
  analysisapi/Pipfile.lock
  analysisapi/README.md
  analysisapi/analysisapi/__init__.py
  analysisapi/analysisapi/__main__.py
  analysisapi/analysisapi/ai_processor/__init__.py
  analysisapi/analysisapi/ai_processor/diary_analyzer.py
  analysisapi/analysisapi/cli.py
  analysisapi/analysisapi/loader/__init__.py
  analysisapi/analysisapi/loader/config_loader.py
  analysisapi/analysisapi/tests/__init__.py
  analysisapi/main.py
Labels: 開発環境改善, AI

#331 ダークモードを追加
  frontend/diary/src/App.vue
  frontend/diary/src/main.ts
  frontend/diary/src/plugins/index.ts
  frontend/diary/src/plugins/vuetify.ts
  frontend/diary/src/stores/counter.ts
  frontend/diary/src/stores/index.ts
Labels: フロントエンドアプリケーション

#300 CLIでのgit手順書作成
  docs/git/CLI/git-cli-manual.md
  docs/git/CLI/images/branch-switching-result.png
  docs/git/CLI/images/change-result.png
  docs/git/CLI/images/check-branch.png
  docs/git/CLI/images/check-create-branch.png
  docs/git/CLI/images/clone-result.png
  docs/git/CLI/images/clone-url.png
  docs/git/CLI/images/git-flowchart-clone.png
  docs/git/CLI/images/git-flowchart-create-push.png
  docs/git/CLI/images/git-flowchart-pull.png
  docs/git/CLI/images/git-flowchart.png
  docs/git/CLI/images/git-management-file-generation-result.png
  docs/git/CLI/images/vscode-branch-switching-result.png
  docs/git/CLI/images/vscode-startup-screen.png
Labels: 開発環境改善

#345 リリースノートのテンプレートを追加
  .github/release.yml
Labels: 開発環境改善

#346 READMEのソフトウェアバージョンを更新
  README.md
Labels: リリース対応

#337 ユーザーのログイン・ログアウト機能を追加
  backend/api-docs/web/api-specification.json
  backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java
  backend/web/src/main/java/com/memoblend/web/controller/UserController.java
  frontend/diary/src/App.vue
  frontend/diary/src/generated/api-client/.openapi-generator/FILES
  frontend/diary/src/generated/api-client/api/diary-api.ts
  frontend/diary/src/generated/api-client/api/user-api.ts
  frontend/diary/src/generated/api-client/models/get-user-response.ts
  frontend/diary/src/generated/api-client/models/index.ts
  frontend/diary/src/generated/api-client/models/problem-detail.ts
  frontend/diary/src/main.ts
  frontend/diary/src/router/authentication/index.ts
  frontend/diary/src/router/diary/index.ts
  frontend/diary/src/router/error/index.ts
  frontend/diary/src/router/index.ts
  frontend/diary/src/services/authentication/authentication-service.ts
  frontend/diary/src/shared/authentication/authentication-guard.ts
  frontend/diary/src/stores/authentication/index.ts
  frontend/diary/src/validation/index.ts
  frontend/diary/src/views/authentication/LoginView.vue
  frontend/package-lock.json
  frontend/package.json
Labels: バックエンドアプリケーション, フロントエンドアプリケーション

#347 リロードしないとログインユーザーが表示されない事象に対応
  frontend/diary/src/stores/authentication/index.ts
Labels: フロントエンドアプリケーション, バグ

#354 LLMを用いた基盤コード作成
  analysisapi/analysisapi/ai_processor/diary_analyzer.py
  analysisapi/analysisapi/cli.py
Labels: AI

#355 ログインしているユーザーの日記のリストを取得する機能を追加
  backend/api-docs/web/api-specification.json
  backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/constant/MessageIdConstants.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryRepository.java
  backend/application-core/src/main/resources/applicationcore/messages.properties
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/MyBatisDiaryRepository.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.xml
  backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java
  backend/web/src/test/java/com/memoblend/web/controller/DiaryControllerTest.java
  frontend/diary/src/generated/api-client/api/diary-api.ts
Labels: バックエンドアプリケーション

#357 日記のユーザーごとの一覧取得のテストを追加
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java
  backend/web/src/test/java/com/memoblend/web/controller/DiaryControllerTest.java
Labels: バックエンドアプリケーション

#352 GUIでのgitのマニュアルを作成
  docs/git/GUI/git-gui-manual.md
  docs/git/GUI/images/add-change-point.png
  docs/git/GUI/images/branch-name-example.png
  docs/git/GUI/images/branch-switching-result.png
  docs/git/GUI/images/change-result.png
  docs/git/GUI/images/check-branch.png
  docs/git/GUI/images/check-create-branch.png
  docs/git/GUI/images/checkout-branch.png
  docs/git/GUI/images/clone-result.png
  docs/git/GUI/images/clone-url.png
  docs/git/GUI/images/commit-example.png
  docs/git/GUI/images/create-branch.png
  docs/git/GUI/images/delete-branch-example.png
  docs/git/GUI/images/git-flowchart-clone.png
  docs/git/GUI/images/git-flowchart-create-push.png
  docs/git/GUI/images/git-flowchart-pull.png
  docs/git/GUI/images/git-flowchart.png
  docs/git/GUI/images/git-management-file-generation-result.png
  docs/git/GUI/images/pull-example.png
  docs/git/GUI/images/select-delete-branch.png
  docs/git/GUI/images/vscode-branch-switching-result.png
  docs/git/GUI/images/vscode-startup-screen.png
Labels: 開発環境改善

#359 GitDiagramを利用してアーキテクチャの概要図を生成し、READMEに追加
  README.md
Labels: 開発環境改善
