Repository MemoBlend/MemoBlend4J, pull requests merged in 2025-07, with the labels that each got.

#620 予定提案をjson形式で出力
  analysisapi/applicationcore/client_application_service.py
  analysisapi/applicationcore/prompt_constants.py
  analysisapi/presentation/controller.py
Labels: AI

#625 日記の提案画面を作成する
  backend/api-docs/web/api-specification.json
  backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java
  backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java
  backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java
  backend/web/src/main/java/com/memoblend/web/controller/dto/diary/GetRecommendedScheduleResponse.java
  frontend/diary/src/generated/api-client/models/get-recommended-schedule-response.ts
  frontend/diary/src/generated/api-client/models/problem-detail.ts
  frontend/diary/src/views/schedule/ScheduleSuggestView.vue
Labels: バックエンドアプリケーション, フロントエンドアプリケーション

#652 gradleの不要なファイルの削除
  backend/application-core/.gitattributes
  backend/application-core/.gitignore
  backend/application-core/build.gradle
  backend/application-core/gradle/wrapper/gradle-wrapper.jar
  backend/application-core/gradle/wrapper/gradle-wrapper.properties
  backend/application-core/gradlew
  backend/application-core/gradlew.bat
  backend/application-core/settings.gradle
  backend/infrastructure/.gitattributes
  backend/infrastructure/.gitignore
  backend/infrastructure/build.gradle
  backend/infrastructure/gradle/wrapper/gradle-wrapper.jar
  backend/infrastructure/gradle/wrapper/gradle-wrapper.properties
  backend/infrastructure/gradlew
  backend/infrastructure/gradlew.bat
  backend/infrastructure/settings.gradle
  backend/system-common/.gitattributes
  backend/system-common/.gitignore
  backend/system-common/build.gradle
  backend/system-common/gradle/wrapper/gradle-wrapper.jar
  backend/system-common/gradle/wrapper/gradle-wrapper.properties
  backend/system-common/gradlew
  backend/system-common/gradlew.bat
  backend/system-common/settings.gradle
  backend/web/.gitattributes
  backend/web/.gitignore
  backend/web/gradle/wrapper/gradle-wrapper.jar
  backend/web/gradle/wrapper/gradle-wrapper.properties
  backend/web/gradlew
  backend/web/gradlew.bat
  backend/web/settings.gradle
Labels: バックエンドアプリケーション, 開発環境改善

#660 lombokを使って値オブジェクトをリファクタリング
  backend/application-core/src/main/java/com/memoblend/applicationcore/appuser/valueobject/Name.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Content.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/CreatedDate.java
  backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Title.java
  backend/infrastructure/src/main/java/com/memoblend/infrastructure/translator/EntityTranslator.java
Labels: 開発環境改善
